import{PanClient as c}from"../../../core/pan-client.mjs";class h extends HTMLElement{static get observedAttributes(){return["resource","columns","key","live"]}constructor(){super(),this.attachShadow({mode:"open"}),this.pc=new c(this),this.items=[],this._offs=[]}connectedCallback(){this.render(),this.#t(),this.#e()}disconnectedCallback(){this._unsubscribeAll()}attributeChangedCallback(){this.render(),this.#t(),this.#e()}get resource(){return(this.getAttribute("resource")||"items").trim()}get columns(){const t=(this.getAttribute("columns")||"").trim();return t?t.split(/\s*,\s*/):null}get key(){return(this.getAttribute("key")||"id").trim()}get live(){const t=(this.getAttribute("live")||"true").toLowerCase();return t!=="false"&&t!=="0"}#t(){this._unsubscribeAll(),this._offs.push(this.pc.subscribe(`${this.resource}.list.state`,t=>{this.items=t?.data?.items||[],this.renderBody()},{retained:!0})),this.live&&this._offs.push(this.pc.subscribe(`${this.resource}.item.state.*`,t=>this.#s(t),{retained:!1}))}#e(){this.pc.publish({topic:`${this.resource}.list.get`,data:{}})}_unsubscribeAll(){try{this._offs.forEach(t=>t&&t())}catch{}this._offs=[]}#s(t){const e=t?.data||{},s=Array.isArray(this.items)?this.items.slice():[],r=this.key;let n=e?.id??e?.item?.[r]??e?.item?.id;if(n==null&&t?.topic){const o=String(t.topic).split(".");n=o[o.length-1]}if(n==null)return;const i=s.findIndex(o=>String(o?.[r]??o?.id)===String(n));if(e.deleted){i>=0&&(s.splice(i,1),this.items=s,this.renderBody());return}if(e.item&&typeof e.item=="object"){i>=0?s[i]=e.item:s.push(e.item),this.items=s,this.renderBody();return}if(e.patch&&typeof e.patch=="object"){const o=i>=0?s[i]:{},d=Object.assign({},o,e.patch);i>=0?s[i]=d:s.push(d),this.items=s,this.renderBody();return}if(e&&typeof e=="object"){const o=i>=0?s[i]:{},d=Object.assign({},o,e);i>=0?s[i]=d:s.push(d),this.items=s,this.renderBody()}}render(){const t=String.raw,e=this.columns||(this.items[0]?Object.keys(this.items[0]):[]);this.shadowRoot.innerHTML=t`
      <style>
        :host{display:block; border:1px solid #ddd; border-radius:8px; overflow:hidden; font:13px/1.4 system-ui, sans-serif}
        table{width:100%; border-collapse:collapse}
        th,td{padding:8px 10px; border-bottom:1px solid #eee; text-align:left}
        tr:hover{ background:#fafafa; cursor:pointer }
        thead th{ background:#f6f6f6; font-weight:600 }
        .empty{ padding:10px; color:#888 }
      </style>
      <table>
        <thead><tr>${e.map(s=>`<th>${s}</th>`).join("")}</tr></thead>
        <tbody></tbody>
      </table>
      <div class="empty" id="empty" hidden>No records.</div>
    `,this.renderBody()}renderBody(){const t=this.shadowRoot.querySelector("tbody");if(!t)return;const e=this.columns||(this.items[0]?Object.keys(this.items[0]):[]);t.innerHTML=this.items.map(r=>`<tr data-id="${r.id??r[this.getAttribute("key")||"id"]}">`+e.map(n=>`<td>${this.#i(r[n])}</td>`).join("")+"</tr>").join("");const s=this.shadowRoot.getElementById("empty");s&&(s.hidden=this.items.length>0),t.querySelectorAll("tr").forEach(r=>{r.addEventListener("click",()=>{const n=r.getAttribute("data-id");this.pc.publish({topic:`${this.resource}.item.select`,data:{id:n}})})})}#i(t){return t==null?"":String(t).replace(/[&<>"']/g,e=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[e])}}customElements.define("pan-data-table",h);var u=h;export{h as PanDataTable,u as default};
