/**
 * A message sent through the PAN bus
 */
export interface PanMessage<T = any> {
  /** Topic name (e.g., "users.list.state") */
  topic: string;

  /** Message payload (any JSON-serializable value) */
  data: T;

  /** Unique message ID (UUID, auto-generated by bus) */
  id?: string;

  /** Timestamp in milliseconds (auto-generated by bus) */
  ts?: number;

  /** If true, message is retained by bus for new subscribers */
  retain?: boolean;

  /** Topic to send reply to (for request/reply pattern) */
  replyTo?: string;

  /** Correlation ID for matching requests and replies */
  correlationId?: string;

  /** Optional metadata headers */
  headers?: Record<string, string>;
}

/**
 * Options for subscribing to topics
 */
export interface SubscribeOptions {
  /** If true, receive retained messages immediately */
  retained?: boolean;

  /** AbortSignal to automatically unsubscribe */
  signal?: AbortSignal;
}

/**
 * Options for making requests
 */
export interface RequestOptions {
  /** Request timeout in milliseconds (default: 5000) */
  timeoutMs?: number;
}
